### ISSUE TITLE
How can I refresh plyr after updating data-plyr-embed-id

### ISSUE THREAD

**Issue by lobothijau** [redxtech/vue-plyr#184]
I try to use data with a method to change `youtubeId` value, but the palyer didn't refreshed when `youtubeId` is updated. How can I refresh the player?

```
  <vue-plyr id="player">
      <div data-plyr-provider="youtube" :data-plyr-embed-id="youtubeId"></div>
  </vue-plyr>
```

**Comment by SriNandan33** [comment]
Facing the same issue here. Can somebody help us please

**Comment by ElioMS** [comment]
Does anyone got the solution? I'm facing the same issue here :(

**Comment by skvair** [comment]
`this.player.source = { 
        type: 'video', 
        sources: [ { src: this.idvideo, provider: 'youtube', },]
      ,}`

Just update the source

**Comment by andreasantonsson** [comment]
I had the same problem and found that the [Vue key attribute](https://vuejs.org/v2/api/#key) does the trick. That way Vue knows it's time to get rid of the old component and create a new one.

```html
<vue-plyr id="player" :key="vimeoVideoID">
  <div data-plyr-provider="youtube" :data-plyr-embed-id="youtubeId" />
</vue-plyr>
```

**Comment by imakeinternet** [comment]
> Vue's [key attribute](https://vuejs.org/v2/api/#key) should do the trick. That way Vue knows it's time to get rid of the old component and create a new one when the `youtubeId` changes.
> 
> ```
> <vue-plyr id="player" :key="youtubeId">
>   <div data-plyr-provider="youtube" :data-plyr-embed-id="youtubeId" />
> </vue-plyr>
> ```

Adding a key attribute solved all my reactivity issues. Thanks for the kick in the pants! :)

**Comment by redxtech** [comment]
Looks like you've already come to the conclusion that I would have: use the `key` attribute. Glad to see it's working.

**Comment by dawadam** [comment]
I think this trick need to be in README.
:+1:

**Comment by AnnikenYT** [comment]
Hello, sorry to have to bump this after so long, but I'm experiencing a kind of issue which I think is related.
Essentially, I have this simple template:
```vue
<template>
  <vue-plyr id='player' :key="id">
    <div data-plyr-provider="youtube" :data-plyr-embed-id="id" />
  </vue-plyr>
</template>
<script setup lang='ts'>

const props = defineProps<{
  id: string;
}>();
```
Now, `id` changes, and the entire app pretty much breaks.
I get this error in console:
```
Uncaught (in promise) TypeError: can't access property "insertBefore", parent is null
```
I've isolated the issue to this component and am using `vue-plyr@7.0.0`.
Any help is appreciated :)

**Comment by dataexcess** [comment]
Why are we forced to rerender the whole component though? This seems unnecessary and expensive. Yet I did not find a way to do it using the normal API...

Why does the following code simply not work?

```
<template>
    <ClientOnly>
        <vue-plyr ref="plyr" :options="{ hideControls: true, autoplay: true, muted: true, volume: 0 }">
            <div data-plyr-provider="vimeo" :data-plyr-embed-id="vimeoId"></div>
        </vue-plyr>
    </ClientOnly>
</template>

<script lang="ts" setup>
import { ref, watchEffect } from 'vue'

const props = defineProps<{
    vimeoId: number
}>()

const plyr = ref<null | any>(null)

watchEffect(() => {
    console.log(props.vimeoId)
    if (plyr.value != undefined) {
        plyr.value.player.source = {
            type: 'video',
            sources: [
                {
                    src: props.vimeoId.toString(),
                    provider: 'vimeo',
                },
            ],
        }
    }
})
</script>
```

when I remove the :key argument I just get a stream of these errors and nothing changes/works:

```
player.js:2 Uncaught (in promise) Error: Unknown player. Probably unloaded.
    at e (player.js:2:12623)
    at new Promise (<anonymous>)
    at Proxy.value (player.js:2:12601)
    at player.js:2:11775
    at new Promise (<anonymous>)
    at Proxy.value (player.js:2:11669)
    at Proxy.value (player.js:2:15030)
    at Proxy.ready2 (plyr.min.mjs:3:77754)
    at Proxy.setup (plyr.min.mjs:3:74303)
    at Proxy.setup (plyr.min.mjs:3:86581)
e @ player.js:2
value @ player.js:2
(anonymous) @ player.js:2
value @ player.js:2
value @ player.js:2
ready2 @ plyr.min.mjs:3
setup @ plyr.min.mjs:3
setup @ plyr.min.mjs:3
(anonymous) @ plyr.min.mjs:3
n2 @ plyr.min.mjs:3
Promise.then (async)
ready2 @ plyr.min.mjs:3
setup @ plyr.min.mjs:3
setup @ plyr.min.mjs:3
(anonymous) @ plyr.min.mjs:3
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
trigger @ reactivity.esm-bundler.js:355
set2 @ reactivity.esm-bundler.js:526
n2 @ plyr.min.mjs:3
setTimeout (async)
value @ plyr.min.mjs:3
change @ plyr.min.mjs:3
set2 @ plyr.min.mjs:3
set2 @ reactivity.esm-bundler.js:519
(anonymous) @ VideoContainer.vue:24
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
getter @ runtime-core.esm-bundler.js:1732
run @ reactivity.esm-bundler.js:187
job @ runtime-core.esm-bundler.js:1809
flushPreFlushCbs @ runtime-core.esm-bundler.js:320
updateComponentPreRender @ runtime-core.esm-bundler.js:5771
componentUpdateFn @ runtime-core.esm-bundler.js:5684
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
patchBlockChildren @ runtime-core.esm-bundler.js:5406
patchElement @ runtime-core.esm-bundler.js:5314
processElement @ runtime-core.esm-bundler.js:5181
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
updateComponent @ runtime-core.esm-bundler.js:5570
processComponent @ runtime-core.esm-bundler.js:5503
patch @ runtime-core.esm-bundler.js:5101
patchBlockChildren @ runtime-core.esm-bundler.js:5406
processFragment @ runtime-core.esm-bundler.js:5469
patch @ runtime-core.esm-bundler.js:5094
patchBlockChildren @ runtime-core.esm-bundler.js:5406
patchElement @ runtime-core.esm-bundler.js:5314
processElement @ runtime-core.esm-bundler.js:5181
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
(anonymous) @ runtime-core.esm-bundler.js:5743
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
triggerRefValue @ reactivity.esm-bundler.js:1003
set value @ reactivity.esm-bundler.js:1048
(anonymous) @ useScrollIndex.ts:21
filter.fn.fn @ index.mjs?v=e55b29b9:66
filter @ index.mjs?v=e55b29b9:125
wrapper @ index.mjs?v=e55b29b9:66
onScroll @ useScrollIndex.ts:16
_createElementVNode.onScroll._cache.<computed>._cache.<computed> @ index.vue:17
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
invoker @ runtime-dom.esm-bundler.js:345
```

when I add the :key argument to the vue-plyr component it does work but I still get a stream of those same warning. They do stop at a certain point, they don't just continue as is the case without the key argument. In any case why do we have to rerender the component? This also causes issues on my website. I am probably doing something wrong. Any help much appreciated!
