### ISSUE TITLE
Error in Nuxt: cannot find module '0'

### ISSUE THREAD

**Issue by gilfuser** [redxtech/vue-plyr#451]
Hi everyone.

I'm getting this error when I try to build y Nuxt app with vue-plyr as a plugin:

```
 ERROR  Cannot find module '0'
Require stack:
- /home/skmecs/Trabalho/3aOrelha.github.io/node_modules/@nuxt/core/dist/core.js

  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
  at Function.resolve (internal/modules/cjs/helpers.js:79:19)
  at p (node_modules/jiti/dist/jiti.js:1:52987)
  at Resolver.v [as _require] (node_modules/jiti/dist/jiti.js:1:53886)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at node_modules/@nuxt/webpack/dist/webpack.js:792:58
  at Array.map (<anonymous>)
  at PostcssConfig.loadPlugins (node_modules/@nuxt/webpack/dist/webpack.js:791:10)
  at PostcssConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:830:14)
  at StyleLoader.postcss (node_modules/@nuxt/webpack/dist/webpack.js:909:39)
  at StyleLoader.apply (node_modules/@nuxt/webpack/dist/webpack.js:969:12)
  at WebpackClientConfig.rules (node_modules/@nuxt/webpack/dist/webpack.js:1357:28)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1537:21)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:1708:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:2016:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2023:12)
```

Any ideas about what is causing it will be much appreciated

**Comment by kissu** [comment]
Hi, can you give more details about your setup please? 🙏🏼

**Comment by d4rkr3pt0r** [comment]
@gilfuser Use the following method:
```
<client-only>
<vue-plyr>
  <audio controls crossorigin playsinline>
   <source :src="audio_url" type="audio/mp3" />
  </audio>
</vue-plyr>
</client-only>
```
```
import 'vue-plyr/dist/vue-plyr.css'
components: {
   'VuePlyr': () => import ('vue-plyr/dist/vue-plyr.ssr.js')
},
```

**Comment by gilfuser** [comment]
Hi @kissu and @d4rkr3pt0r. Thank you
Please don't close this for being stalled for so long. I'm trying the suggested method and will report next about the result.
